### PR TITLE
Update to waf 2.0.21

### PR DESCRIPTION
**Pull request by autoantwort**
This fixes the build/the verification of the certificate. See [your](@piem) last comments on #312

### CODE REVIEW

**Comment by autoantwort** [comment]
This is also the reason why the pipeline of #318 and  #321 is failing

**Comment by autoantwort** [comment]
Idk why the Codecov/project score changed. I did not change a single line of code.

**Comment by autoantwort** [comment]
@piem This would also fix #325. Can you merge this, it is only a version update for waf where only the cert changed.

**Comment by piem** [comment]
hi @autoantwort 

thanks for the patch and the bump. next time, please sign your commits so that I can merge them in!

cheers, piem

**Comment by autoantwort** [comment]
Sorry, I didn't know that. Next time I will sign them.

**Pull request closed without merging**
