### PR TITLE
Fixed spelling error: "condidence" to "confidence"

### PR DESCRIPTION
**Pull request by THE-COB**

### CODE REVIEW

**Comment by THE-COB** [comment]
Not really sure why this failed the Travis CI build, I just fixed the spelling of a label on one of the matplotlib axes...

**Comment by piem** [comment]
hi @THE-COB,

thanks for the fix, I will merge it in, travis failure is unrelated, needs some update.

best, piem

**Comment by THE-COB** [comment]
Awesome, thanks for getting back to me.

**Comment by piem** [comment]
hello,

this has been merged in `master` now, thanks @THE-COB !

cheers, piem

**Pull request merged**
