### PR TITLE
Windows build (for Universal Windows) along an example in C#.

### PR DESCRIPTION
**Pull request by aybe**
Hello,

Here's my contribution to the project :
- a Windows Runtime Component accessible from any language UWP apps are available
- the static library backing the component as they are better kept separate
- a C# example, it accepts a WAV/MP3/FLAC then detects tempos and onsets
- gitignore update for Windows / Visual Studio

Notes :
- I have not linked against libsndfile or FFTW
- I simplified the usage of the library, there are SetData and GetData methods for sending samples and getting results respectively:

https://github.com/aybe/aubio/blob/develop/windows/winrt/aubio/AubioComponent/Aubio.h#L11

https://github.com/aybe/aubio/blob/develop/windows/winrt/aubio/AubioComponent/Aubio.h#L91

https://github.com/aybe/aubio/blob/develop/windows/winrt/aubio/AubioComponent/Aubio.h#L102

https://github.com/aybe/aubio/blob/develop/windows/winrt/aubio/AubioComponent.Example/MainPage.xaml.cs#L23
- So far I have implemented tempo, onsets and pitch with a few properties such as tolerance and silence threshold but would like to implement the rest in the future.

Let me know what you think,

Thanks !

### CODE REVIEW

**Comment by piem** [comment]
Thank you @aybe, the VS build will be much needed. However, I think the C# example would be best in its own project. I will test all this as soon as possible.

**Comment by aybe** [comment]
Alright, when I have some free time I'll implement the rest of the API :D

**Comment by piem** [comment]
hi @aybe 

For the windows build, I'm not sure about including such large files for VS: I don't use it myself, so it would be for me hard to maintain it. Also, I see you deleted your repository there, so I'm closing this for now.

Still, a C# component would be really nice! Any news on this? 

cheers, piem

**Comment by aybe** [comment]
Alright for closing !

Sorry no plans for such component as I've completely stopped audio programming due to a lack of time :(

**Pull request closed without merging**
